[package]
name = "adapt"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
snafu = { workspace = true }
sea-query = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
mockall = { workspace = true }
